import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const beSeedPath = path.join(__dirname, '../../BE Project Management/src/seed.ts');
const beSupportSeedPath = path.join(__dirname, '../../BE Project Management/src/seed-support.ts');
const outputPath = path.join(__dirname, './data.ts');

console.log('Reading backend seed files...');

if (!fs.existsSync(beSeedPath)) {
  console.error(`Error: Backend seed file not found at ${beSeedPath}`);
  process.exit(1);
}

if (!fs.existsSync(beSupportSeedPath)) {
  console.error(`Error: Backend support seed file not found at ${beSupportSeedPath}`);
  process.exit(1);
}

const seedContent = fs.readFileSync(beSeedPath, 'utf8');
const supportSeedContent = fs.readFileSync(beSupportSeedPath, 'utf8');

// Match const rawProjects: RawProject[] = [ ... ];
const projectsRegex = /const rawProjects:\s*RawProject\[\]\s*=\s*([\s\S]+?);\r?\n\r?\nfunction/m;
const projectsMatch = seedContent.match(projectsRegex);

if (!projectsMatch) {
  console.error('Error: Could not find rawProjects array in seed.ts');
  process.exit(1);
}

// Match const rawTickets: RawSupportTicket[] = [ ... ];
const ticketsRegex = /const rawTickets:\s*RawSupportTicket\[\]\s*=\s*([\s\S]+?);\r?\n\r?\nfunction/m;
const ticketsMatch = supportSeedContent.match(ticketsRegex);

if (!ticketsMatch) {
  console.error('Error: Could not find rawTickets array in seed-support.ts');
  process.exit(1);
}

const outputContent = `// Automatically generated by generate-data.js. Do not edit directly.

export interface RawProject {
  no: number;
  name: string;
  po: string;
  so: string;
  picClient: string;
  description: string;
  mandays: number;
  status: string;
  platform: string;
  startDate: string;
  endDate: string;
  ba: string[];
  uiux: string[];
  fe: string[];
  be: string[];
  remarks: string;
  updateDate: string;
  repositoryLink?: string;
  timelineLink?: string;
}

export interface RawSupportDetail {
  subIssue: string;
  hoursSpent: number;
  status: string;
  startDate: string;
  endDate: string;
  devBeNames?: string;
  platform?: string;
}

export interface RawSupportTicket {
  no: number;
  projectName: string;
  poNumber: string;
  soNumber: string;
  customer: string;
  issue: string;
  hours: number;
  status: string;
  platform: string;
  startDate: string;
  endDate: string;
  businessAnalyst?: string;
  uiUx?: string;
  devFe?: string;
  devBe?: string;
  attachments?: string;
  updateDate?: string;
  notes?: string;
  details?: RawSupportDetail[];
}

export const rawProjects: RawProject[] = ${projectsMatch[1]};

export const rawTickets: RawSupportTicket[] = ${ticketsMatch[1]};
`;

fs.writeFileSync(outputPath, outputContent, 'utf8');
console.log(`Successfully extracted data to ${outputPath}`);
