/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Create a new user/member */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id */
        get: operations["UsersController_findOne"];
        /** Update user */
        put: operations["UsersController_update"];
        post?: never;
        /** Deactivate user (soft delete) */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roles */
        get: operations["RolesController_findAll"];
        put?: never;
        /** Create a new role */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get role by id */
        get: operations["RolesController_findOne"];
        /** Update a role */
        put: operations["RolesController_update"];
        post?: never;
        /** Delete a role */
        delete: operations["RolesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all role rates */
        get: operations["RoleRatesController_findAll"];
        put?: never;
        /** Create a new role rate */
        post: operations["RoleRatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global role rates (no project tied) */
        get: operations["RoleRatesController_getGlobalRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates/project/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get role rates specific to a project */
        get: operations["RoleRatesController_getProjectRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get role rate by id */
        get: operations["RoleRatesController_findOne"];
        /** Update role rate */
        put: operations["RoleRatesController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all master projects */
        get: operations["MasterProjectsController_findAll"];
        put?: never;
        /** Create a new master project */
        post: operations["MasterProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get master project details */
        get: operations["MasterProjectsController_findOne"];
        /** Update master project */
        put: operations["MasterProjectsController_update"];
        post?: never;
        /** Delete master project */
        delete: operations["MasterProjectsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all projects */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Create a new project */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: operations["ProjectsController_findOne"];
        /** Update project */
        put: operations["ProjectsController_update"];
        post?: never;
        /** Delete project */
        delete: operations["ProjectsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project members */
        get: operations["ProjectsController_getMembers"];
        put?: never;
        /** Add member to project */
        post: operations["ProjectsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove member from project */
        delete: operations["ProjectsController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new project activity */
        post: operations["ProjectActivitiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities/project/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all activities for a project */
        get: operations["ProjectActivitiesController_findByProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity details */
        get: operations["ProjectActivitiesController_findOne"];
        /** Update a project activity */
        put: operations["ProjectActivitiesController_update"];
        post?: never;
        /** Delete a project activity */
        delete: operations["ProjectActivitiesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Quick update activity progress percentage */
        patch: operations["ProjectActivitiesController_updateProgress"];
        trace?: never;
    };
    "/api/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all POs */
        get: operations["PurchaseOrdersController_findAll"];
        put?: never;
        /** Create a new PO */
        post: operations["PurchaseOrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get PO details */
        get: operations["PurchaseOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase-orders/project/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get POs by Project */
        get: operations["PurchaseOrdersController_findByProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all SOs */
        get: operations["SalesOrdersController_findAll"];
        put?: never;
        /** Create a new SO */
        post: operations["SalesOrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get SO details */
        get: operations["SalesOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales-orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update SO Status */
        put: operations["SalesOrdersController_updateStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/po-so-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a member to PO/SO */
        post: operations["PoSoMembersController_assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/po-so-members/po/{poId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get members by PO */
        get: operations["PoSoMembersController_findByPo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/po-so-members/{id}/actuals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update actual mandays */
        put: operations["PoSoMembersController_updateActuals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all support tickets */
        get: operations["SupportTicketsController_findAll"];
        put?: never;
        /** Create a new support ticket */
        post: operations["SupportTicketsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ticket details */
        get: operations["SupportTicketsController_findOne"];
        /** Update support ticket */
        put: operations["SupportTicketsController_update"];
        post?: never;
        /** Delete support ticket */
        delete: operations["SupportTicketsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets/{id}/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ticket assignees */
        get: operations["SupportTicketsController_getAssignees"];
        put?: never;
        /** Assign a member to ticket */
        post: operations["SupportTicketsController_addAssignee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets/{id}/assignees/{assigneeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an assignee allocation */
        put: operations["SupportTicketsController_updateAssignee"];
        post?: never;
        /** Remove an assignee from ticket */
        delete: operations["SupportTicketsController_removeAssignee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate preview of invoice calculations */
        post: operations["BillingController_generatePreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an invoice based on actuals */
        post: operations["BillingController_createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all invoices */
        get: operations["BillingController_findAllInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice details */
        get: operations["BillingController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current logged in user */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseResponseDto: {
            /** @example true */
            success: boolean;
            /** @example Operation successful */
            message?: string;
        };
        UserResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            email: string;
            fullName: string;
            employeeId?: string;
            avatarUrl?: string;
            isActive: boolean;
            passwordHash?: string;
        };
        Object: Record<string, never>;
        CreateUserDto: {
            /** @example John Doe */
            fullName: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Password123 */
            password: string;
            /** @example EMP-001 */
            employeeId?: string;
            avatarUrl?: string;
        };
        UpdateUserDto: {
            /** @example John Doe Updated */
            fullName?: string;
            /** @example EMP-002 */
            employeeId?: string;
            avatarUrl?: string;
            /** @example true */
            isActive?: boolean;
        };
        RoleResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            code: string;
            name: string;
            description?: string;
        };
        CreateRoleDto: {
            /** @example PM */
            code: string;
            /** @example Project Manager */
            name: string;
            /** @example Handles project management */
            description?: string;
        };
        SuccessResponseDto: {
            /** @example true */
            success: boolean;
            /** @example Operation successful */
            message?: string;
        };
        MasterProjectResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            projectCode: string;
            name: string;
            description?: string;
            platform?: string;
            isActive: boolean;
        };
        ProjectResponseDto: {
            id: number;
            projectId: number;
            picClient?: string;
            picInternal?: string;
            customer?: string;
            parentProjectId?: number;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            actualStart?: string;
            /** Format: date-time */
            actualEnd?: string;
            /** @enum {string} */
            status: "PLANNING" | "IN PROGRESS" | "SIT" | "UAT" | "CLOSED" | "ON HOLD" | "CANCELLED" | "FUT";
            totalMandays?: number;
            progressPct?: number;
            repositoryLink?: string;
            timelineLink?: string;
            timelineRemark?: string;
            remarks?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            project?: components["schemas"]["MasterProjectResponseDto"];
            parentProject?: components["schemas"]["ProjectResponseDto"];
        };
        RoleRateResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            roleId: number;
            projectId?: number;
            ratePerManday: number;
            ratePerHour: number;
            currency: string;
            /** Format: date-time */
            effectiveFrom: string;
            /** Format: date-time */
            effectiveUntil?: string;
            isActive: boolean;
            role?: components["schemas"]["RoleResponseDto"];
            project?: components["schemas"]["ProjectResponseDto"];
        };
        CreateRoleRateDto: {
            roleId: number;
            projectId?: number;
            ratePerManday: number;
            ratePerHour?: number;
            /** @default IDR */
            currency: string;
            /** @example 2026-01-01 */
            effectiveFrom: string;
            /** @example 2026-12-31 */
            effectiveUntil?: string;
        };
        CreateMasterProjectDto: {
            name: string;
            description?: string;
            platform?: string;
        };
        CreateProjectDto: {
            /** @description Master project ID (FK to master_projects) */
            projectId: number;
            picClient?: string;
            customer?: string;
            picInternal?: string;
            /** @description Parent project ID (self-ref for support projects) */
            parentProjectId?: number;
            startDate?: string;
            endDate?: string;
            actualStart?: string;
            actualEnd?: string;
            totalMandays?: number;
            /** @enum {string} */
            status?: "PLANNING" | "IN PROGRESS" | "SIT" | "UAT" | "CLOSED" | "ON HOLD" | "CANCELLED" | "FUT";
            timelineRemark?: string;
            progressPct?: number;
            repositoryLink?: string;
            timelineLink?: string;
            remarks?: string;
        };
        UpdateProjectDto: {
            /** @description Master project ID (FK to master_projects) */
            projectId?: number;
            picClient?: string;
            customer?: string;
            picInternal?: string;
            /** @description Parent project ID (self-ref for support projects) */
            parentProjectId?: number;
            startDate?: string;
            endDate?: string;
            actualStart?: string;
            actualEnd?: string;
            totalMandays?: number;
            /** @enum {string} */
            status?: "PLANNING" | "IN PROGRESS" | "SIT" | "UAT" | "CLOSED" | "ON HOLD" | "CANCELLED" | "FUT";
            timelineRemark?: string;
            progressPct?: number;
            repositoryLink?: string;
            timelineLink?: string;
            remarks?: string;
        };
        ProjectMemberResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            projectId: number;
            userId: number;
            roleId: number;
            assignedMandays: number;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate?: string;
            isActive: boolean;
            user?: components["schemas"]["UserResponseDto"];
            role?: components["schemas"]["RoleResponseDto"];
        };
        AddProjectMemberDto: {
            userId: number;
            roleId: number;
            assignedMandays?: number;
        };
        ProjectActivityResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            projectId: number;
            parentId?: number;
            activityName: string;
            description?: string;
            feature?: string;
            subFeature?: string;
            details?: string;
            durationDays: number;
            mandays: number;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            actualStart?: string;
            /** Format: date-time */
            actualEnd?: string;
            progressPct: number;
            phase: string;
            assignedToId?: number;
            sortOrder: number;
            isMilestone: boolean;
            assignedTo?: components["schemas"]["UserResponseDto"];
        };
        CreateProjectActivityDto: {
            projectId: number;
            parentId?: number;
            activityName: string;
            description?: string;
            feature?: string;
            subFeature?: string;
            details?: string;
            durationDays?: number;
            mandays?: number;
            startDate?: string;
            endDate?: string;
            progressPct?: number;
            /** @enum {string} */
            phase?: "FCAB" | "REQUIREMENT" | "ANALYSIS" | "DESIGN" | "SRS" | "CRQ" | "DEVELOPMENT" | "UT SIT" | "TRA TC" | "REVIEW" | "SIT" | "UAT" | "NFT" | "SECURITY" | "RFS" | "FUT";
            assignedToId?: number;
            sortOrder?: number;
            isMilestone?: boolean;
        };
        UpdateProjectActivityDto: {
            projectId?: number;
            parentId?: number;
            activityName?: string;
            description?: string;
            feature?: string;
            subFeature?: string;
            details?: string;
            durationDays?: number;
            mandays?: number;
            startDate?: string;
            endDate?: string;
            progressPct?: number;
            /** @enum {string} */
            phase?: "FCAB" | "REQUIREMENT" | "ANALYSIS" | "DESIGN" | "SRS" | "CRQ" | "DEVELOPMENT" | "UT SIT" | "TRA TC" | "REVIEW" | "SIT" | "UAT" | "NFT" | "SECURITY" | "RFS" | "FUT";
            assignedToId?: number;
            sortOrder?: number;
            isMilestone?: boolean;
        };
        UpdateProgressDto: {
            /** @description Progress percentage (0-100) */
            progressPct: number;
        };
        PurchaseOrderResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            poNumber: string;
            poName: string;
            projectId: number;
            customer: string;
            description?: string;
            totalMandays: number;
            totalAmount: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "IN PROGRESS" | "COMPLETED" | "CLOSED" | "CANCELLED";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            signedDate?: string;
            documentUrl?: string;
            remarks?: string;
            isActive: boolean;
            createdById: number;
            project?: components["schemas"]["ProjectResponseDto"];
        };
        CreatePurchaseOrderDto: {
            poName: string;
            projectId: number;
            customer: string;
            description?: string;
        };
        SalesOrderResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            soNumber: string;
            soName: string;
            projectId: number;
            purchaseOrderId: number;
            customer: string;
            description?: string;
            totalMandays: number;
            totalAmount: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "IN PROGRESS" | "DELIVERED" | "INVOICED" | "PAID" | "CLOSED" | "CANCELLED";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            signedDate?: string;
            documentUrl?: string;
            remarks?: string;
            isActive: boolean;
            createdById: number;
            project?: components["schemas"]["ProjectResponseDto"];
            purchaseOrder?: components["schemas"]["PurchaseOrderResponseDto"];
            po?: components["schemas"]["PurchaseOrderResponseDto"];
        };
        CreateSalesOrderDto: {
            soName: string;
            poId: number;
            projectId: number;
            description?: string;
        };
        PoSoMemberResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            poId: number;
            soId?: number;
            projectMemberId: number;
            roleId: number;
            actualMandays: number;
            actualHours: number;
            ratePerManday: number;
            totalCost: number;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            isBillable: boolean;
            po?: components["schemas"]["PurchaseOrderResponseDto"];
            so?: components["schemas"]["SalesOrderResponseDto"];
            projectMember?: components["schemas"]["ProjectMemberResponseDto"];
            role?: components["schemas"]["RoleResponseDto"];
        };
        AssignPoSoMemberDto: {
            poId: number;
            soId?: number;
            projectMemberId: number;
            roleId: number;
            actualMandays?: number;
            actualHours?: number;
        };
        SupportTicketResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            ticketCode: string;
            masterProjectId?: number;
            customer?: string;
            picClient?: string;
            issueTitle: string;
            issueDescription?: string;
            hoursSpent: number;
            mandaysSpent: number;
            /** @enum {string} */
            status: "OPEN" | "IN PROGRESS" | "DEV DONE" | "SIT DONE" | "UAT DONE" | "DONE" | "ON HOLD" | "CANCELLED";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            folderAttachment?: string;
            notes?: string;
            /** Format: date-time */
            updateDate?: string;
            isActive: boolean;
            masterProject?: components["schemas"]["MasterProjectResponseDto"];
            assignees?: components["schemas"]["SupportTicketAssigneeResponseDto"][];
        };
        SupportTicketAssigneeResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            supportTicketId: number;
            userId: number;
            roleId?: number;
            hoursSpent: number;
            /** @enum {string} */
            status: "OPEN" | "IN PROGRESS" | "DONE" | "ON HOLD";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            notes?: string;
            supportTicket?: components["schemas"]["SupportTicketResponseDto"];
            user?: components["schemas"]["UserResponseDto"];
            role?: components["schemas"]["RoleResponseDto"];
        };
        CreateSupportTicketDto: {
            /** @description Master project ID (FK to master_projects) */
            masterProjectId?: number;
            /** @description Master project name (used to find/create master project if masterProjectId is not provided) */
            masterProjectName?: string;
            customer?: string;
            picClient?: string;
            issueTitle: string;
            issueDescription?: string;
        };
        CreateSupportTicketAssigneeDto: {
            /** @description User ID of the assigned member */
            userId: number;
            /** @description Role ID of the assigned member */
            roleId?: number;
            hoursSpent?: number;
            /** @enum {string} */
            status?: "OPEN" | "IN PROGRESS" | "DONE" | "ON HOLD";
            startDate?: string;
            endDate?: string;
            notes?: string;
        };
        UpdateSupportTicketAssigneeDto: {
            /** @description Role ID of the assigned member */
            roleId?: number;
            hoursSpent?: number;
            /** @enum {string} */
            status?: "OPEN" | "IN PROGRESS" | "DONE" | "ON HOLD";
            startDate?: string;
            endDate?: string;
            notes?: string;
        };
        UpdateSupportTicketDto: {
            masterProjectId?: number;
            masterProjectName?: string;
            customer?: string;
            picClient?: string;
            issueTitle?: string;
            issueDescription?: string;
            hoursSpent?: number;
            mandaysSpent?: number;
            status?: string;
            notes?: string;
        };
        GenerateInvoiceDto: {
            poId: number;
            projectId: number;
            startDate: string;
            endDate: string;
            taxRate?: number;
        };
        BillingInvoiceDetailResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            billingInvoiceId: number;
            roleId?: number;
            description: string;
            totalMandays: number;
            ratePerManday: number;
            amount: number;
            role?: components["schemas"]["RoleResponseDto"];
        };
        BillingInvoiceResponseDto: {
            invoiceNumber: string;
            projectId: number;
            poId?: number;
            soId?: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            totalAmount: number;
            /** @enum {string} */
            status: "DRAFT" | "SENT" | "PAID" | "OVERDUE" | "CANCELLED";
            isActive: boolean;
            createdById: number;
            /** Format: date-time */
            createdAt: string;
            project?: components["schemas"]["ProjectResponseDto"];
            po?: components["schemas"]["PurchaseOrderResponseDto"];
            so?: components["schemas"]["SalesOrderResponseDto"];
            createdBy?: components["schemas"]["UserResponseDto"];
            details?: components["schemas"]["BillingInvoiceDetailResponseDto"][];
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["UserResponseDto"];
        };
        RegisterDto: {
            /** @example John Doe */
            fullName: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Password123 */
            password: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"][];
                    };
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"][];
                    };
                };
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"];
                    };
                };
            };
        };
    };
    RolesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"];
                    };
                };
            };
        };
    };
    RolesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"];
                    };
                };
            };
        };
    };
    RolesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SuccessResponseDto"];
                    };
                };
            };
        };
    };
    RoleRatesController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"][];
                    };
                };
            };
        };
    };
    RoleRatesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"];
                    };
                };
            };
        };
    };
    RoleRatesController_getGlobalRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"][];
                    };
                };
            };
        };
    };
    RoleRatesController_getProjectRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"][];
                    };
                };
            };
        };
    };
    RoleRatesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"];
                    };
                };
            };
        };
    };
    RoleRatesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"];
                    };
                };
            };
        };
    };
    MasterProjectsController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["MasterProjectResponseDto"][];
                    };
                };
            };
        };
    };
    MasterProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMasterProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["MasterProjectResponseDto"];
                    };
                };
            };
        };
    };
    MasterProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["MasterProjectResponseDto"];
                    };
                };
            };
        };
    };
    MasterProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["MasterProjectResponseDto"];
                    };
                };
            };
        };
    };
    MasterProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SuccessResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectMemberResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectMemberResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectActivitiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectActivityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_findByProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectActivityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SuccessResponseDto"];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_updateProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProgressDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"][];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_findByProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"][];
                    };
                };
            };
        };
    };
    SalesOrdersController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"][];
                    };
                };
            };
        };
    };
    SalesOrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSalesOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"];
                    };
                };
            };
        };
    };
    SalesOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"];
                    };
                };
            };
        };
    };
    SalesOrdersController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"];
                    };
                };
            };
        };
    };
    PoSoMembersController_assign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPoSoMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PoSoMemberResponseDto"];
                    };
                };
            };
        };
    };
    PoSoMembersController_findByPo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PoSoMemberResponseDto"][];
                    };
                };
            };
        };
    };
    PoSoMembersController_updateActuals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PoSoMemberResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                perPage?: number;
                /** @description Sort format (e.g. -createdAt or name) */
                sort?: string;
                /** @description Search keyword */
                search?: string;
                /** @description Column filters (key-value object or JSON string) */
                filter?: components["schemas"]["Object"];
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"][];
                    };
                };
            };
        };
    };
    SupportTicketsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportTicketDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSupportTicketDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SuccessResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_getAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketAssigneeResponseDto"][];
                    };
                };
            };
        };
    };
    SupportTicketsController_addAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportTicketAssigneeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketAssigneeResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_updateAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                assigneeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSupportTicketAssigneeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketAssigneeResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_removeAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                assigneeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SuccessResponseDto"];
                    };
                };
            };
        };
    };
    BillingController_generatePreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInvoiceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingController_createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInvoiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["BillingInvoiceResponseDto"];
                    };
                };
            };
        };
    };
    BillingController_findAllInvoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["BillingInvoiceResponseDto"][];
                    };
                };
            };
        };
    };
    BillingController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["BillingInvoiceResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
    };
}
