/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all roles */
        get: operations["RolesController_findAll"];
        put?: never;
        /** Create a new role */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get role by id */
        get: operations["RolesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all role rates */
        get: operations["RoleRatesController_findAll"];
        put?: never;
        /** Create a new role rate */
        post: operations["RoleRatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global role rates (no project tied) */
        get: operations["RoleRatesController_getGlobalRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/role-rates/project/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get role rates specific to a project */
        get: operations["RoleRatesController_getProjectRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all projects */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Create a new project */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: operations["ProjectsController_findOne"];
        /** Update project */
        put: operations["ProjectsController_update"];
        post?: never;
        /** Delete project */
        delete: operations["ProjectsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project members */
        get: operations["ProjectsController_getMembers"];
        put?: never;
        /** Add member to project */
        post: operations["ProjectsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new project activity */
        post: operations["ProjectActivitiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities/project/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all activities for a project */
        get: operations["ProjectActivitiesController_findByProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity details */
        get: operations["ProjectActivitiesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all POs */
        get: operations["PurchaseOrdersController_findAll"];
        put?: never;
        /** Create a new PO */
        post: operations["PurchaseOrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get PO details */
        get: operations["PurchaseOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase-orders/project/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get POs by Project */
        get: operations["PurchaseOrdersController_findByProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all SOs */
        get: operations["SalesOrdersController_findAll"];
        put?: never;
        /** Create a new SO */
        post: operations["SalesOrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get SO details */
        get: operations["SalesOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales-orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update SO Status */
        put: operations["SalesOrdersController_updateStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/po-so-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a member to PO/SO */
        post: operations["PoSoMembersController_assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/po-so-members/po/{poId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get members by PO */
        get: operations["PoSoMembersController_findByPo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/po-so-members/{id}/actuals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update actual mandays */
        put: operations["PoSoMembersController_updateActuals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all support tickets */
        get: operations["SupportTicketsController_findAll"];
        put?: never;
        /** Create a new support ticket */
        post: operations["SupportTicketsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ticket details */
        get: operations["SupportTicketsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/support-tickets/{id}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ticket details/sub-issues */
        get: operations["SupportTicketsController_getDetails"];
        put?: never;
        /** Add detail/sub-issue to ticket */
        post: operations["SupportTicketsController_addDetail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate preview of invoice calculations */
        post: operations["BillingController_generatePreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an invoice based on actuals */
        post: operations["BillingController_createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all invoices */
        get: operations["BillingController_findAllInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice details */
        get: operations["BillingController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current logged in user */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseResponseDto: {
            /** @example true */
            success: boolean;
            /** @example Operation successful */
            message?: string;
        };
        RoleResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            code: string;
            name: string;
            description?: string;
        };
        CreateRoleDto: {
            /** @example PM */
            code: string;
            /** @example Project Manager */
            name: string;
            /** @example Handles project management */
            description?: string;
        };
        RoleRateResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            roleId: number;
            projectId?: number;
            ratePerManday: number;
            ratePerHour: number;
            currency: string;
            /** Format: date-time */
            effectiveFrom: string;
            /** Format: date-time */
            effectiveUntil?: string;
            isActive: boolean;
            role?: components["schemas"]["RoleResponseDto"];
        };
        CreateRoleRateDto: {
            roleId: number;
            projectId?: number;
            ratePerManday: number;
            ratePerHour?: number;
            /** @default IDR */
            currency: string;
            /** @example 2026-01-01 */
            effectiveFrom: string;
            /** @example 2026-12-31 */
            effectiveUntil?: string;
        };
        ProjectResponseDto: {
            projectCode: string;
            name: string;
            description?: string;
            picClient?: string;
            picInternal?: string;
            platform?: string;
            customer?: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate?: string;
            /** @enum {string} */
            status: "PLANNING" | "IN_PROGRESS" | "SIT" | "UAT" | "CLOSED" | "ON_HOLD" | "CANCELLED" | "FUT";
            timelineRemark?: string;
            isActive: boolean;
        };
        CreateProjectDto: {
            name: string;
            description?: string;
            picClient?: string;
            platform?: string;
            customer?: string;
        };
        UpdateProjectDto: {
            name?: string;
            description?: string;
            picClient?: string;
            platform?: string;
            customer?: string;
            /** @enum {string} */
            status?: "PLANNING" | "IN_PROGRESS" | "SIT" | "UAT" | "CLOSED" | "ON_HOLD" | "CANCELLED" | "FUT";
            timelineRemark?: string;
            startDate?: string;
            endDate?: string;
        };
        UserResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            email: string;
            fullName: string;
            employeeId?: string;
            avatarUrl?: string;
            isActive: boolean;
        };
        ProjectMemberResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            projectId: number;
            userId: number;
            roleId: number;
            secondaryRoleId?: number;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate?: string;
            isActive: boolean;
            user?: components["schemas"]["UserResponseDto"];
            role?: components["schemas"]["RoleResponseDto"];
            secondaryRole?: components["schemas"]["RoleResponseDto"];
        };
        AddProjectMemberDto: {
            userId: number;
            roleId: number;
            secondaryRoleId?: number;
            assignedMandays?: number;
        };
        ProjectActivityResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            projectId: number;
            createdById: number;
            title: string;
            description?: string;
            /** Format: date-time */
            activityDate: string;
            mandaysLog: number;
            project?: components["schemas"]["ProjectResponseDto"];
        };
        CreateProjectActivityDto: {
            projectId: number;
            parentId?: number;
            activityName: string;
            description?: string;
            durationDays?: number;
            mandays?: number;
        };
        PurchaseOrderResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            poNumber: string;
            poName: string;
            projectId: number;
            customer: string;
            description?: string;
            totalMandays: number;
            totalAmount: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "IN_PROGRESS" | "COMPLETED" | "CLOSED" | "CANCELLED";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            signedDate?: string;
            documentUrl?: string;
            remarks?: string;
            isActive: boolean;
            createdById: number;
            project?: components["schemas"]["ProjectResponseDto"];
        };
        CreatePurchaseOrderDto: {
            poName: string;
            projectId: number;
            customer: string;
            description?: string;
        };
        SalesOrderResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            soNumber: string;
            soName: string;
            projectId: number;
            purchaseOrderId: number;
            customer: string;
            description?: string;
            totalMandays: number;
            totalAmount: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "IN_PROGRESS" | "DELIVERED" | "INVOICED" | "PAID" | "CLOSED" | "CANCELLED";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            signedDate?: string;
            documentUrl?: string;
            remarks?: string;
            isActive: boolean;
            createdById: number;
            project?: components["schemas"]["ProjectResponseDto"];
            purchaseOrder?: components["schemas"]["PurchaseOrderResponseDto"];
        };
        CreateSalesOrderDto: {
            soName: string;
            poId: number;
            projectId: number;
            description?: string;
        };
        PoSoMemberResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            poId: number;
            soId?: number;
            projectMemberId: number;
            roleId: number;
            actualMandays: number;
            actualHours: number;
            ratePerManday: number;
            totalCost: number;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            isBillable: boolean;
            po?: components["schemas"]["PurchaseOrderResponseDto"];
            so?: components["schemas"]["SalesOrderResponseDto"];
            projectMember?: components["schemas"]["ProjectMemberResponseDto"];
            role?: components["schemas"]["RoleResponseDto"];
        };
        AssignPoSoMemberDto: {
            poId: number;
            soId?: number;
            projectMemberId: number;
            roleId: number;
            actualMandays?: number;
            actualHours?: number;
        };
        SupportTicketResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            ticketCode: string;
            projectId?: number;
            projectName: string;
            picClient?: string;
            issueTitle: string;
            issueDescription?: string;
            hoursSpent: number;
            mandaysSpent: number;
            /** @enum {string} */
            status: "OPEN" | "IN_PROGRESS" | "DEV_DONE" | "SIT_DONE" | "UAT_DONE" | "DONE" | "ON_HOLD" | "CANCELLED";
            platform?: string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            businessAnalystId?: number;
            uiUxId?: number;
            devFeId?: number;
            devBeId?: number;
            folderAttachment?: string;
            notes?: string;
            /** Format: date-time */
            updateDate?: string;
            isActive: boolean;
            project?: components["schemas"]["ProjectResponseDto"];
            businessAnalyst?: components["schemas"]["UserResponseDto"];
            uiUx?: components["schemas"]["UserResponseDto"];
            devFe?: components["schemas"]["UserResponseDto"];
            devBe?: components["schemas"]["UserResponseDto"];
        };
        CreateSupportTicketDto: {
            projectName: string;
            projectId?: number;
            issueTitle: string;
            issueDescription?: string;
        };
        SupportTicketDetailResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            supportTicketId: number;
            subIssue: string;
            hoursSpent: number;
            /** @enum {string} */
            status: "OPEN" | "IN_PROGRESS" | "DONE" | "ON_HOLD";
            platform?: string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            devBeNames?: string;
            supportTicket?: components["schemas"]["SupportTicketResponseDto"];
        };
        CreateSupportTicketDetailDto: {
            subIssue: string;
            hoursSpent?: number;
        };
        GenerateInvoiceDto: {
            poId: number;
            projectId: number;
            startDate: string;
            endDate: string;
            taxRate?: number;
        };
        BillingInvoiceDetailResponseDto: {
            id: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: number;
            updatedBy?: number;
            billingInvoiceId: number;
            roleId?: number;
            description: string;
            totalMandays: number;
            ratePerManday: number;
            amount: number;
            role?: components["schemas"]["RoleResponseDto"];
        };
        BillingInvoiceResponseDto: {
            invoiceNumber: string;
            projectId: number;
            poId?: number;
            soId?: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            totalAmount: number;
            /** @enum {string} */
            status: "DRAFT" | "SENT" | "PAID" | "OVERDUE" | "CANCELLED";
            isActive: boolean;
            createdById: number;
            /** Format: date-time */
            createdAt: string;
            project?: components["schemas"]["ProjectResponseDto"];
            po?: components["schemas"]["PurchaseOrderResponseDto"];
            so?: components["schemas"]["SalesOrderResponseDto"];
            createdBy?: components["schemas"]["UserResponseDto"];
            details?: components["schemas"]["BillingInvoiceDetailResponseDto"][];
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["UserResponseDto"];
        };
        RegisterDto: {
            /** @example John Doe */
            fullName: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Password123 */
            password: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    RolesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"][];
                    };
                };
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"];
                    };
                };
            };
        };
    };
    RolesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleResponseDto"];
                    };
                };
            };
        };
    };
    RoleRatesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"][];
                    };
                };
            };
        };
    };
    RoleRatesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"];
                    };
                };
            };
        };
    };
    RoleRatesController_getGlobalRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"][];
                    };
                };
            };
        };
    };
    RoleRatesController_getProjectRates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["RoleRateResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectResponseDto"];
                    };
                };
            };
        };
    };
    ProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectMemberResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectMemberResponseDto"];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectActivityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_findByProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"][];
                    };
                };
            };
        };
    };
    ProjectActivitiesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["ProjectActivityResponseDto"];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"][];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"];
                    };
                };
            };
        };
    };
    PurchaseOrdersController_findByProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PurchaseOrderResponseDto"][];
                    };
                };
            };
        };
    };
    SalesOrdersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"][];
                    };
                };
            };
        };
    };
    SalesOrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSalesOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"];
                    };
                };
            };
        };
    };
    SalesOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"];
                    };
                };
            };
        };
    };
    SalesOrdersController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SalesOrderResponseDto"];
                    };
                };
            };
        };
    };
    PoSoMembersController_assign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPoSoMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PoSoMemberResponseDto"];
                    };
                };
            };
        };
    };
    PoSoMembersController_findByPo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PoSoMemberResponseDto"][];
                    };
                };
            };
        };
    };
    PoSoMembersController_updateActuals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["PoSoMemberResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"][];
                    };
                };
            };
        };
    };
    SupportTicketsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportTicketDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketResponseDto"];
                    };
                };
            };
        };
    };
    SupportTicketsController_getDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketDetailResponseDto"][];
                    };
                };
            };
        };
    };
    SupportTicketsController_addDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportTicketDetailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["SupportTicketDetailResponseDto"];
                    };
                };
            };
        };
    };
    BillingController_generatePreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInvoiceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingController_createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInvoiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["BillingInvoiceResponseDto"];
                    };
                };
            };
        };
    };
    BillingController_findAllInvoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["BillingInvoiceResponseDto"][];
                    };
                };
            };
        };
    };
    BillingController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["BillingInvoiceResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
        };
    };
}
